spring:
  application:
    name: zyit.spring.cloud.web.user.feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html

server:
  port: 8766

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#开启feign熔断器的配置，feign中已经集成了熔断器，无需添加依赖
feign:
  hystrix:
    enabled: true